### ISSUE TITLE
Calling Resolved/Erased function fails at EvalUnionCaseTest

### ISSUE THREAD

**Issue by tylerhartwig** [fsprojects/FSharp.Compiler.PortaCode#13]
Hi, 

Following the guide of Fabulous Live Update and Giraffe.HotReload, I'm trying to implement HotReload for Bolero Elmish. I've been able to successfully resolve the "update" function from the MVU pipeline, but when I call the erased function, the following exception occurs:

<img width="775" alt="Screen Shot 2019-04-07 at 12 13 11 PM" src="https://user-images.githubusercontent.com/9355929/55687097-9aae6980-592e-11e9-8838-305fbba1d316.png">

What's interesting is that it's resolving the actual union value, rather than the structure describing it. 

The code I'm attempting to hot reload is as follows:
```
type Model =
    {
        value: int
    }

let initModel =
    {
        value = 0
    }


type Message =
    | Increment
    | Decrement

let update (message : Message) (model : Model) =
    match message with
    | Increment ->
        { model with value = model.value + 1 }, Cmd.none
    | Decrement ->
        { model with value = model.value - 1 }, Cmd.none

let view model dispatch =
    concat [
        button [on.click (fun _ -> dispatch Decrement)] [text "-"]
        span [] [textf " %i " model.value]
        button [on.click (fun _ -> dispatch Increment)] [text "+"]
    ]


type Updater(update) =
    member __.UniqueUpdate message model = update message model

let myHotReload = Updater(update)
```

And the code that is resolving the `myHotReload` value:

```
    let handleUpdate (updater : ProgramUpdater<'msg, 'model>) (files : (string * DFile)[]) =
        printfn "Created interpreter! %A" interpreter

        lock interpreter (fun () ->
            files |> Array.iter (fun (fileName, file) -> interpreter.AddDecls file.Code)
            files |> Array.iter (fun (fileName, file) -> interpreter.EvalDecls (envEmpty, file.Code))
          )

        let mem = tryFindMemberInFiles "myHotReload" files
        match mem with
        | Some (def, expr) ->
            try
                printfn "Found member!"
                let entity = interpreter.ResolveEntity(def.EnclosingEntity)
                printfn "Got entity! %A" entity

                let (def, memberValue) = interpreter.GetExprDeclResult(entity, def.Name)
                printfn "Got member value! %A" memberValue

                let value = getVal memberValue
                printfn "Got Value!: %A" value

                match value with
                | :? ObjectValue as x ->
                    let (ObjectValue v) = x
                    let updater = Map.find "update" v.Value

                    printfn "Found update %A" updater
                    let erasedUpdater = updater :?> obj -> obj -> obj * Cmd<obj>

                    printfn "Successfully cast: %A" erasedUpdater
                    let model = initModel
                    let message = Message.Increment

                    printfn "Calling update"
                    let newSet = erasedUpdater message model
                    printfn "Got new value %A" newSet
                | :? Updater as updater ->
                    printfn "Found Updater!"
                    let model = initModel
                    let message = Message.Increment

                    printfn "calling Updater!"
                    let newSet = updater.UniqueUpdate message model
                    printfn "Got new values! %A" newSet

            with e ->
                printfn "Got exception: %A" e

        | None ->
            printfn "could not find member"
```

More interesting details, the `value` here is resolving as an `ObjectValue` rather than as the `Updater` type as I expected. I've tried resolving the `update` function various ways as well, packaged in a type, as a method itself, however I always receive the previously mentioned exception.

I'm not sure if there is an issue in the way I'm resolving the types, or a bug in the interpreter, any advice or help would be greatly appreciated. Thanks :) 

EDIT:

Update, the reason the object was resolving as `ObjectValue` is because of how I set up my projects, I've fixed that now, but the issue still remains.

**Comment by dsyme** [comment]
@tylerhartwig It's hard for me to see the bug from the above.  Is there a way to create a stand-alone repro that is a PortaCode test case?

**Comment by tylerhartwig** [comment]
@dsyme 

I have a pretty minimal repository with the setup here: https://github.com/tylerhartwig/Bolero.HotReload
-- The HotReload.Listener is what I've been using to do the interpreting and debugging, with HotReload.Elmish being the code which gets reloaded. 

I'll look into the tests today and see if I can come up with a proper PortaCode test for it tonight.

**Comment by dsyme** [comment]
So on [this line](https://github.com/tylerhartwig/Bolero.HotReload/blob/master/src/HotReload.Library/Library.fs#L104) do you get an Updater or a UnionValue? I think I'd expect to see a UnionValue here?  (I might be wrong, hard to tell without running)

**Comment by tylerhartwig** [comment]
I get an Updater on that line.

The problem lies in [this line](https://github.com/fsprojects/FSharp.Compiler.PortaCode/blob/0c6686bcc518246d879bb3d0e3cd4cdbbc72d5ad/src/Interpreter.fs#L1182)

Here this line is returning the actual union instantiation (of type `Message`), in this case `Increment` or `Decrement`. If I'm understanding the code correctly, it should be of `UnionValue` type instead.

**Comment by dsyme** [comment]
@tylerhartwig Yes, I can't see why that wouldn't be a UnionValue.  All the branches on which `Message` was produced should wrap in `UnionValue`. Odd.  Suggest debugging (breakpointing) the creation/consumption of the message values

**Comment by tylerhartwig** [comment]
@dsyme Yes, when I debugged this I followed it down to resolving the `Message` value from [this line](https://github.com/fsprojects/FSharp.Compiler.PortaCode/blob/0c6686bcc518246d879bb3d0e3cd4cdbbc72d5ad/src/Interpreter.fs#L734).

Is this a cached value? or is the value being resolved here? I'm guessing it's a cached value and that I'll need to back-track and find where it's being resolved and added to the environment.

**Comment by dsyme** [comment]
> Is this a cached value? or is the value being resolved here? I'm guessing it's a cached value and that I'll need to back-track and find where it's being resolved and added to the environment.

I think that's just reading the value from a local. You'd have to trace back further.  

But it's just very hard to see how an unwrapped Message object could be produced - the `EvalNewUnionCase` wraps it, and no one unwraps it except `EvalUnionCaseTest` and `EvalUnionCaseGet`, both of which consume (discard) the unwrapped value.

**Comment by tylerhartwig** [comment]
Okay thanks, this helps a lot, I'll jump in again tonight and see how it's getting unwrapped and added :)

**Comment by tylerhartwig** [comment]
Okay, after a little research it's getting added to the `Vals` map on the environment [here](https://github.com/fsprojects/FSharp.Compiler.PortaCode/blob/0c6686bcc518246d879bb3d0e3cd4cdbbc72d5ad/src/Interpreter.fs#L1061) on the bind call in the dynamically made function from `EvalLambda` (I'm guessing this isn't too surprising). 

We jump into that anonymous function after making this [call](https://github.com/tylerhartwig/Bolero.HotReload/blob/a48161a233d9b3a5317576f5af91bf948b69e015/src/HotReload.Listener/ListenerController.fs#L45) (listed below as well).

```
    let updater = handleUpdate files
    let newSet = updater.Update (Decrement) (initModel)
    printfn "Got new set: %A" newSet
```

Am I calling this method wrong? do I need to wrap the arguments myself before passing it into the interpreted function? or do I need to call the function via the interpreter in some fashion? 

The best I could tell from Fabulous and HotReload.Giraffe I just needed to call it normally, but I very well could have missed something.

**Comment by dsyme** [comment]
@tylerhartwig I'm not totally sure - am I right that `updater` has type `ProgramUpdater<obj,obj...>` and the use of `obj` might be obscuring something here?  

Getting the "update" function field from the object here feels suspicious, it's like accessing the internals of the interpreter. https://github.com/tylerhartwig/Bolero.HotReload/blob/master/src/HotReload.Library/Library.fs#L92.  If you could simplify things so that you didn't do that the issue might go away

**Comment by tylerhartwig** [comment]
@dsyme 
No, in this case it is of type [Updater](https://github.com/tylerhartwig/Bolero.HotReload/blob/a48161a233d9b3a5317576f5af91bf948b69e015/src/HotReload.Library/Library.fs#L104).

I previously was pulling the function out of the internals because I did not setup my project references correctly and the library did not have proper knowledge of the type to resolve it properly. I should delete that from the repo now (I'll update it now).

Regardless, calling it from the internals, calling it from within an object, and resolving it directly as a function have all yielded this same exception. 😞

**Comment by dsyme** [comment]
BTW you might also want to look at FCSWatch eg. https://github.com/humhei/FCSWatch/

**Comment by dsyme** [comment]
Also since you may be able to compile-on-device with Bolero maybe you don't need PortaCode at all?  Just wondering.

**Comment by tylerhartwig** [comment]
Interesting, I've not explored these other two ideas. FSCWatch seems intriguing and may be a great boon for development with Bolero. 

Part of the attractive part with PortaCode is I could likely maintain the current Elmish model when swapping out the View and Update layers. Since I'm unfamiliar with the other methods I'm not sure if they could do that as well. Additionally following Giraffe.HotReload seemed very straightforward.

**Comment by tylerhartwig** [comment]
@dsyme

I was reviewing this again just now, I think I could potentially fix this bug (if it's a bug).

Is it right for `EvalLambda` to receive unwrapped union case values? Or should it always deal with wrapped values? 

In this case it seems that UnionCaseTest should be able to support comparing against unwrapped union case values (I believe this is used to interpret pattern matches on unions). 

If not, then whatever is calling the method being created in EvalLambda should be wrapping a value and is not. Going to try and write a fix tonight, and want to make sure I take the correct approach.

**Comment by dsyme** [comment]
> Is it right for EvalLambda to receive unwrapped union case values? Or should it always deal with wrapped values?

* Yes for union values defined in referenced DLLs.  They should just be the boxed value.

* No for union values defined in the file being interpreted.  They should always be UnionValue

> In this case it seems that UnionCaseTest should be able to support comparing against unwrapped union case values (I believe this is used to interpret pattern matches on unions).

I think we should never see unwrapped union values (i.e. without UnionCase) for union types defined in the interpreted code.

**Comment by tylerhartwig** [comment]
> * No for union values defined in the file being interpreted.  They should always be UnionValue

I believe this is where the problems lies in my case, `Message` is a type in a file being interpreted. It should be the job of the object or dynamically created instance method to wrap this in a UnionValue, and I'm guessing that's where the solution would need to happen.

**Comment by dsyme** [comment]
> I believe this is where the problems lies in my case, Message is a type in a file being interpreted. It should be the job of the object or dynamically created instance method to wrap this in a UnionValue, and I'm guessing that's where the solution would need to happen.

I'm still not understanding the origin of this value, sorry.  The only place in the interpreter (NewUnionCase) where we create a union value we do wrap in `UnionValue`.  Where is this being created?

**Comment by tylerhartwig** [comment]
Sorry, I probably didn't explain it very clearly.

1. I resolve the value I want to work [here](https://github.com/tylerhartwig/Bolero.HotReload/blob/a4890aecf6a72d20531f7cbb19b41dbcd07b99bd/src/HotReload.Library/Library.fs#L90)
2. I call this method, passing in the hard, boxed types (of type Message and Model) [here](https://github.com/tylerhartwig/Bolero.HotReload/blob/a4890aecf6a72d20531f7cbb19b41dbcd07b99bd/src/HotReload.Listener/ListenerController.fs#L45)
3. The resolved, interpreted object call `bind` [here](https://github.com/fsprojects/FSharp.Compiler.PortaCode/blob/0c6686bcc518246d879bb3d0e3cd4cdbbc72d5ad/src/Interpreter.fs#L1061)
    This is the point at which the unwrapped, `Message` and `Model` values end up in the `env`
4. EvalUnionCaseTest retrieves the unwrapped `Message` and `Model` values [here](https://github.com/fsprojects/FSharp.Compiler.PortaCode/blob/0c6686bcc518246d879bb3d0e3cd4cdbbc72d5ad/src/Interpreter.fs#L1182)

**Comment by dsyme** [comment]
Is [this file](https://github.com/tylerhartwig/Bolero.HotReload/blob/a4890aecf6a72d20531f7cbb19b41dbcd07b99bd/src/HotReload.Listener/ListenerController.fs#L45) also being interpreted?

**Comment by tylerhartwig** [comment]
No, this is the one utilizing the Hot Reload functionality.

**Comment by dsyme** [comment]
OK - well, this isn't really supported.  You're passing in a value based on a "compiled" version of the type into interpreted code.

When invoking the interpreted code, you should not pass in any values related to the interpreted code unless those values were created by the interpreter.

**Comment by tylerhartwig** [comment]
Interesting, I must be mis-understanding how Giraffe.HotReload and Fabulous swap out their runners then. Nonetheless it should be easy enough to derive the correct types to pass the update function using the interpreter.

**Comment by tylerhartwig** [comment]
Closing this as I believe it's been resolved, but I'll summarize my understanding of this problem.

Any functions, classes, or code that is interpreted, will expect interpreted values and return interpreted values/types, if those types are included in the files being interpreted.

However, HotReload.Giraffe uses the interpretation to produce and use a Giraffe-specific type that can be used with compiled code. I assume this is because this type is resolved differently because the Giraffe library is not being interpreted in this case.
